// ALERTS
export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

// FETCH PLAYLIST
export const FETCH_PLAYLISTS_REQUEST = "FETCH_PLAYLISTS_REQUEST";
export const FETCH_PLAYLISTS_SUCCESS = "FETCH_PLAYLISTS_SUCCESS";
export const FETCH_PLAYLISTS_FAILURE = "FETCH_PLAYLISTS_FAILURE";
 
  
export const DELETE_PLAYLIST = "DELETE_PLAYLIST"; 


